POST http://localhost:8080/api/account/createAccount HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkRZdGlMUkFjZFJORjZWcFpWaERnMyJ9.eyJpc3MiOiJodHRwczovL2Rldi1mNTFvZmNob2ppeWUzaWUyLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwODkyNTQxNDM5Njg4MzYyNTE1NCIsImF1ZCI6WyJodHRwczovL3Byb2plY3QtY29tbXVuaXR5LWZpbmRlci9hcGkvIiwiaHR0cHM6Ly9kZXYtZjUxb2ZjaG9qaXllM2llMi51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjk4MDk4MzQxLCJleHAiOjE2OTgxODQ3NDEsImF6cCI6IkFGZER2SWM5SzNvaXNIN3hFcXNCRW1yem0xbThvYmdCIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCJ9.dUrC1HZpl6j1HgOAtMMgU3otVS1DrafOQatl3mMLsVJRQxIdqLF8DgybtiNQkKouQXHLL64mJhprEX8rYygpahqyQT4hoRLUY22wlcK6w_guGc2-GeFKiQOQHRJWV93jIpuY1_dVv0GlxwG5kLmhwjGENDtkhndvjtP17nLsxWcruZHfmHWUaAA6qiC43Rn8M11BjUhzwrLT1x5xnHHV7mnPGeruC_aBb-3tuNKBXt-iLwXlfNqhgys92o2BRpcPKOmBAbkMNQCGl_TI6Jry-if2QhYMWeSvrBcumMZXJ8BwAIsa60-30SmkyZWmodandSt3m3Hb0IFg-IHj3E5hDA

{
    "username": "sample",
    "password": "papaddada",
    "email" : "sample@gmail.com"
}

###

POST http://localhost:8080/api/account/createAccount HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkRZdGlMUkFjZFJORjZWcFpWaERnMyJ9.eyJpc3MiOiJodHRwczovL2Rldi1mNTFvZmNob2ppeWUzaWUyLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwODkyNTQxNDM5Njg4MzYyNTE1NCIsImF1ZCI6WyJodHRwczovL3Byb2plY3QtY29tbXVuaXR5LWZpbmRlci9hcGkvIiwiaHR0cHM6Ly9kZXYtZjUxb2ZjaG9qaXllM2llMi51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjk4MDk4MzQxLCJleHAiOjE2OTgxODQ3NDEsImF6cCI6IkFGZER2SWM5SzNvaXNIN3hFcXNCRW1yem0xbThvYmdCIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCJ9.dUrC1HZpl6j1HgOAtMMgU3otVS1DrafOQatl3mMLsVJRQxIdqLF8DgybtiNQkKouQXHLL64mJhprEX8rYygpahqyQT4hoRLUY22wlcK6w_guGc2-GeFKiQOQHRJWV93jIpuY1_dVv0GlxwG5kLmhwjGENDtkhndvjtP17nLsxWcruZHfmHWUaAA6qiC43Rn8M11BjUhzwrLT1x5xnHHV7mnPGeruC_aBb-3tuNKBXt-iLwXlfNqhgys92o2BRpcPKOmBAbkMNQCGl_TI6Jry-if2QhYMWeSvrBcumMZXJ8BwAIsa60-30SmkyZWmodandSt3m3Hb0IFg-IHj3E5hDA

{ 
    "username": "sample2",
    "password": "papaddada",
    "email" : "sample2@gmail.com"
}

###

POST http://localhost:8080/api/friendRequest/send HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkRZdGlMUkFjZFJORjZWcFpWaERnMyJ9.eyJpc3MiOiJodHRwczovL2Rldi1mNTFvZmNob2ppeWUzaWUyLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwODkyNTQxNDM5Njg4MzYyNTE1NCIsImF1ZCI6WyJodHRwczovL3Byb2plY3QtY29tbXVuaXR5LWZpbmRlci9hcGkvIiwiaHR0cHM6Ly9kZXYtZjUxb2ZjaG9qaXllM2llMi51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjk4MDk4MzQxLCJleHAiOjE2OTgxODQ3NDEsImF6cCI6IkFGZER2SWM5SzNvaXNIN3hFcXNCRW1yem0xbThvYmdCIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCJ9.dUrC1HZpl6j1HgOAtMMgU3otVS1DrafOQatl3mMLsVJRQxIdqLF8DgybtiNQkKouQXHLL64mJhprEX8rYygpahqyQT4hoRLUY22wlcK6w_guGc2-GeFKiQOQHRJWV93jIpuY1_dVv0GlxwG5kLmhwjGENDtkhndvjtP17nLsxWcruZHfmHWUaAA6qiC43Rn8M11BjUhzwrLT1x5xnHHV7mnPGeruC_aBb-3tuNKBXt-iLwXlfNqhgys92o2BRpcPKOmBAbkMNQCGl_TI6Jry-if2QhYMWeSvrBcumMZXJ8BwAIsa60-30SmkyZWmodandSt3m3Hb0IFg-IHj3E5hDA

{
    "sender" : "sample@gmail.com",
    "receiver" : "sample2@gmail.com"
}

###

GET http://localhost:8080/api/friendRequest/getAllRequest?receiverEmail=sample2@gmail.com HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkRZdGlMUkFjZFJORjZWcFpWaERnMyJ9.eyJpc3MiOiJodHRwczovL2Rldi1mNTFvZmNob2ppeWUzaWUyLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwODkyNTQxNDM5Njg4MzYyNTE1NCIsImF1ZCI6WyJodHRwczovL3Byb2plY3QtY29tbXVuaXR5LWZpbmRlci9hcGkvIiwiaHR0cHM6Ly9kZXYtZjUxb2ZjaG9qaXllM2llMi51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjk4MDk4MzQxLCJleHAiOjE2OTgxODQ3NDEsImF6cCI6IkFGZER2SWM5SzNvaXNIN3hFcXNCRW1yem0xbThvYmdCIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCJ9.dUrC1HZpl6j1HgOAtMMgU3otVS1DrafOQatl3mMLsVJRQxIdqLF8DgybtiNQkKouQXHLL64mJhprEX8rYygpahqyQT4hoRLUY22wlcK6w_guGc2-GeFKiQOQHRJWV93jIpuY1_dVv0GlxwG5kLmhwjGENDtkhndvjtP17nLsxWcruZHfmHWUaAA6qiC43Rn8M11BjUhzwrLT1x5xnHHV7mnPGeruC_aBb-3tuNKBXt-iLwXlfNqhgys92o2BRpcPKOmBAbkMNQCGl_TI6Jry-if2QhYMWeSvrBcumMZXJ8BwAIsa60-30SmkyZWmodandSt3m3Hb0IFg-IHj3E5hDA

###
DELETE http://localhost:8080/api/friendRequest/decline?sender=sample@gmail.com&receiver=sample2@gmail.com HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkRZdGlMUkFjZFJORjZWcFpWaERnMyJ9.eyJpc3MiOiJodHRwczovL2Rldi1mNTFvZmNob2ppeWUzaWUyLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwODkyNTQxNDM5Njg4MzYyNTE1NCIsImF1ZCI6WyJodHRwczovL3Byb2plY3QtY29tbXVuaXR5LWZpbmRlci9hcGkvIiwiaHR0cHM6Ly9kZXYtZjUxb2ZjaG9qaXllM2llMi51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjk4MDk4MzQxLCJleHAiOjE2OTgxODQ3NDEsImF6cCI6IkFGZER2SWM5SzNvaXNIN3hFcXNCRW1yem0xbThvYmdCIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCJ9.dUrC1HZpl6j1HgOAtMMgU3otVS1DrafOQatl3mMLsVJRQxIdqLF8DgybtiNQkKouQXHLL64mJhprEX8rYygpahqyQT4hoRLUY22wlcK6w_guGc2-GeFKiQOQHRJWV93jIpuY1_dVv0GlxwG5kLmhwjGENDtkhndvjtP17nLsxWcruZHfmHWUaAA6qiC43Rn8M11BjUhzwrLT1x5xnHHV7mnPGeruC_aBb-3tuNKBXt-iLwXlfNqhgys92o2BRpcPKOmBAbkMNQCGl_TI6Jry-if2QhYMWeSvrBcumMZXJ8BwAIsa60-30SmkyZWmodandSt3m3Hb0IFg-IHj3E5hDA
